set_property SRC_FILE_INFO {cfile:c:/Users/Cesar/Documents/GitHub/FPinGA/ip/xfft_1/ip/xfft_1/xfft_1/xfft_1_in_context.xdc rfile:../../../ip/xfft_1/ip/xfft_1/xfft_1/xfft_1_in_context.xdc id:1 order:EARLY scoped_inst:fft} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Cesar/Documents/GitHub/FPinGA/ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc rfile:../../../ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc id:2 order:EARLY scoped_inst:tone_detection/first_div} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Cesar/Documents/GitHub/FPinGA/ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc rfile:../../../ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc id:3 order:EARLY scoped_inst:tone_detection/second_div} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Cesar/Documents/GitHub/FPinGA/ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc rfile:../../../ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc id:4 order:EARLY scoped_inst:tone_detection/third_div} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Cesar/Documents/GitHub/FPinGA/ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc rfile:../../../ip/div_gen_0/ip/div_gen_0/div_gen_0/div_gen_0_in_context.xdc id:5 order:EARLY scoped_inst:fft_spacing} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Cesar/Documents/GitHub/FPinGA/xdc/top_level.xdc rfile:../../../xdc/top_level.xdc id:6} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins fft/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fft]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins tone_detection/first_div/aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells tone_detection/first_div]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins tone_detection/second_div/aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells tone_detection/second_div]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins tone_detection/third_div/aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells tone_detection/third_div]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 1000 [get_pins fft_spacing/aclk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells fft_spacing]
set_property src_info {type:XDC file:6 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name gclk -waveform {0.000 4.000} -add [get_ports clk_100mhz]
set_property src_info {type:XDC file:6 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mic*]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells fft]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells fft_spacing]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells tone_detection/first_div]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells tone_detection/second_div]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells tone_detection/third_div]
